Added a patch that can be enabled by an ENV variable to force HTTPS for streamServer
sleeyax/stremio-streaming-server pull request #12
Opened 2022-07-05 04:11 UTC by kvn1351

The solution for issue #10 had as a consequence that the `streamServer` within the URL would always be set to http although the container is called via https (via the proxy).

While it's clear why this is happening, since it's proxying after all, it's very tedious and disruptive to the UX. Especially on mobile systems. 

Therefore it's crucial to be able to force the stremServer's protocol to https.

2022-07-05 13:48 UTC, sleeyax requested changes
Looks alright, see review for some quality changes though. I think eventually we'll want a more robust way to allow users to specify 'patches', but I'll work on that myself after this PR.

Edit: with 'more robust way' I mean via accessing the environment variables in the `start.sh` script and NOT by passing the value as a parameter at the  ENTRYPOINT statement.

2022-07-05 13:48 UTC, sleeyax commented on Dockerfile
> +ADD start.sh /stremio
We're already in workdir `/stremio` so you can just do:

```suggestion
COPY start.sh .
```

2022-07-05 13:48 UTC, sleeyax commented on start.sh
> +echo "$1"
Remove this.

2022-07-05 13:51 UTC, sleeyax requested changes

2022-07-05 13:51 UTC, sleeyax commented on Dockerfile
> +RUN ["chmod", "+x", "/stremio/start.sh"]
Rename this to:
```suggestion
RUN chmod +x start.sh
```
... for consistency with the other RUN statements. I don't think exec form is required for chmod to apply.

2022-07-05 20:40 UTC, kvn1351 commented
I have implemented all of the changes. It's also not passing the value as a parameter anymore. I left that in from testing.

2022-07-06 00:34 UTC, sleeyax requested changes
Thanks, this looks much better already. Just a few more nitpicking things and then it should be good to merge!

2022-07-06 00:34 UTC, sleeyax commented on start.sh
> +#!/bin/bash
Does a shell shebang work too? Can't test it myself rn.
```suggestion
#!/bin/sh
```

2022-07-06 00:34 UTC, sleeyax commented on Dockerfile
> +ENTRYPOINT sh /stremio/start.sh
Maybe this can be simplified even more, would appreciate if you can test this though.
```suggestion
ENTRYPOINT sh start.sh
```

2022-07-06 14:17 UTC, kvn1351 commented
I've squashed the commits and made the changes you requested. What do you think?

2022-07-06 14:27 UTC, kvn1351 commented on Dockerfile
> +ENTRYPOINT ./start.sh
start.sh only gives a not found error. Hence the ./

2022-07-06 19:41 UTC, sleeyax requested changes

2022-07-06 19:41 UTC, sleeyax commented on Dockerfile
> +WORKDIR stremio
Workdir paths should be absolute according to Dockerfile conventions so please leave it as `/stremio`.

2022-07-06 19:51 UTC, sleeyax commented on Dockerfile
> +WORKDIR stremio
I made the change for you, don't want to keep you waiting much longer.

2022-07-06 19:52 UTC, merged